name: Unit Testing
on:
  push:
  pull_request:
jobs:
  phpunit:
    name: PHP ${{ matrix.php }} / ${{ matrix.platform }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental == true }}
    services:
      mysql:
        image: mariadb:10.11
        env:
          MARIADB_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=10
    strategy:
      fail-fast: false
      matrix:
        include:
          # Minimum supported WordPress.
          - { php: '7.4', platform: '6.2' }
          - { php: '8.0', platform: '6.2' }
          - { php: '8.2', platform: '6.2' }
          # Latest WordPress.
          - { php: '7.4', platform: 'latest' }
          - { php: '8.1', platform: 'latest' }
          - { php: '8.3', platform: 'latest' }
          - { php: '8.4', platform: 'latest' }
          - { php: '8.5', platform: 'latest', experimental: true }
          # ClassicPress.
          - { php: '7.4', platform: 'classicpress:2.7.3' }
          - { php: '8.1', platform: 'classicpress:2.7.3' }
          - { php: '8.3', platform: 'classicpress:2.7.3' }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          tools: composer
          extensions: mysqli
      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3
      - name: Install test environment
        run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 '${{ matrix.platform }}'
      - name: Run PHPUnit
        run: composer phpunit
